# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Delete(object):
    def setupUi(self, Form_Delete):
        Form_Delete.setObjectName("Form_Delete")
        Form_Delete.resize(400, 188)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        Form_Delete.setFont(font)
        self.label = QtWidgets.QLabel(Form_Delete)
        self.label.setGeometry(QtCore.QRect(11, 11, 286, 24))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Form_Delete)
        self.comboBox.setGeometry(QtCore.QRect(10, 60, 211, 41))
        self.comboBox.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form_Delete)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 371, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(Form_Delete)
        QtCore.QMetaObject.connectSlotsByName(Form_Delete)

    def retranslateUi(self, Form_Delete):
        _translate = QtCore.QCoreApplication.translate
        Form_Delete.setWindowTitle(_translate("Form_Delete", "Form"))
        self.label.setText(_translate("Form_Delete", "Выберите актив для удаления:"))
        self.pushButton.setText(_translate("Form_Delete", "Удалить"))
        self.pushButton_2.setText(_translate("Form_Delete", "Отмена"))
