# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\forecast.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Forecast(object):
    def setupUi(self, Form_Forecast):
        Form_Forecast.setObjectName("Form_Forecast")
        Form_Forecast.setEnabled(True)
        Form_Forecast.resize(500, 600)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form_Forecast)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form_Forecast)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(23)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(Form_Forecast)
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.currency_combobox = QtWidgets.QComboBox(Form_Forecast)
        self.currency_combobox.setMinimumSize(QtCore.QSize(125, 0))
        self.currency_combobox.setMaximumSize(QtCore.QSize(101, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        self.currency_combobox.setFont(font)
        self.currency_combobox.setObjectName("currency_combobox")
        self.horizontalLayout.addWidget(self.currency_combobox)
        self.label_3 = QtWidgets.QLabel(Form_Forecast)
        self.label_3.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(Form_Forecast)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalSlider = QtWidgets.QSlider(Form_Forecast)
        self.horizontalSlider.setMaximumSize(QtCore.QSize(400, 16777215))
        self.horizontalSlider.setMaximum(120)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tableWidget = QtWidgets.QTableWidget(Form_Forecast)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(145)
        self.verticalLayout_2.addWidget(self.tableWidget)

        self.retranslateUi(Form_Forecast)
        QtCore.QMetaObject.connectSlotsByName(Form_Forecast)

    def retranslateUi(self, Form_Forecast):
        _translate = QtCore.QCoreApplication.translate
        Form_Forecast.setWindowTitle(_translate("Form_Forecast", "Прогноз"))
        self.label.setText(_translate("Form_Forecast", "0"))
        self.label_4.setText(_translate("Form_Forecast", "Баланс"))
        self.label_3.setText(_translate("Form_Forecast", "через:"))
        self.label_2.setText(_translate("Form_Forecast", "0"))
